- src/releasing/releaser.sh
This way we don't interfere with GitHub's tarball naming.
Fixes #60.
> Only tag template libraries with release version

- src/releasing/releaser.sh
Avoid race-condition by ensuring target directories exist first.
Fixes #68 (which by extension fixes quattor/configuration-modules-core#311).
> Copy metaconfig templates to template-library-core at release

- src/scripts/build_all_repos.sh
build_all_repos builds packages for all Quattor repos, without any quattor modules 
required in the perl INC path(s).
The script currently assumes that all non-Quattor dependencies for running 
the unittests are present (e.g. panc, mvn, git, the perl test modules, ...).
> Add build_all_repos script

- src/releasing/quattorpoddoc.py
@jrha I updated the script so it recreates exactly what is in https://github.com/quattor/configuration-modules-core/tree/docs
So:
- removed headers user for jekyll
- adapted data structure (docs/components/<mdfile>)
- write mkdocs.yml
should save you some sed time. :)
> move to readthedocs

- src/scripts/get-template-library
(required for this script to work on some Debian derivatives)
> get-template-library: ensure that bash is used

- src/scripts/build_all_repos.sh
also set the QUATTOR_TEST_TEMPLATE_LIBRARY_CORE environment variable in (so you can also run the tests on repositories that are checked out elsewhere)
fixes #76
> build_all_repos: add QUATTOR_TEST_TEMPLATE_LIBRARY_CORE in env.sh

- src/releasing/releaser.sh
Currently we rely on the unit tests to produce the pan templates as a side effect.
This is indeed ugly, see https://github.com/quattor/maven-tools/issues/40.
> Run tests to produce metaconfig pan templates during release

- quattor-client/pom.xml
Otherwise the version number will not be included
> Package filtered copy of quattor-release

- src/releasing/releaser.sh
The time taken to build a release has been increasing steadily and I don't expect things to get any better, currently each build takes about 1.5 hours wall time.
The most time consuming parts of the release is running the unit tests, which we should absolutely do. However, they currently they get run at least three times, once during `release:prepare`, again during `release:perform` and again when we build the `metaconfig` templates.
`release:prepare` updates the snapshot, tags the git repository, runs the tests and builds packages.
`release:perform` runs the tests, builds packages and uploads artifacts to the LAL Nexus.
My proposal is that we no longer run `release:perform` and therefore do not push artifacts to the LAL Nexus repository during releases. AFAIK we only push the `pom`, …
> Remove release:perform from maven invocation

- src/scripts/trac2md.py
Wrapper over pandoc to work around the missing tracwiki input format.
Has been used and tested for https://github.com/quattor/quattor.github.com/pull/178.
> add a script to convert a tracwiki file into markdown

- .gitignore
PyCharm is an IDE like Eclipse for Python-based projects. When it is used it creates a `.idea` directory for things specific to PyCharm. There is no reason to put it in the repo (in the same way as Eclipse `.project` is ignored).
> .gitignore: add PyCharm work directory

- src/releasing/releaser.sh
It is quite easy to forget this, which prevents tests running and metaconfig templates from being built.
> releaser: Check that a reference core template library has been set

- src/releasing/releaser.sh
This is the correct way to achieve quattor/template-library-core#99.
> releaser: Include opennebula when publishing aii templates

- src/releasing/quattorpoddoc.py
I updated the script so it adds a first simple parsing of pan annotations from the schema.pan in the configuration-core-modules.
It now also generates documentation for CCM and CAF. (AII and maven-tools should be coming soon).
so it produces this:
https://docs-test-comps.readthedocs.org/en/latest/
I am no true programmer so pointers to the code are very welcome!
> support CAF and CCM and pan annotations

- quattor-repo/src/quattor.repo
$base and $release do not work, so use $basearch and $releasever as per el5 and el6 docs.
https://www.centos.org/docs/5/html/5.2/Deployment_Guide/s1-yum-useful-variables.html
The docs say $arch is the value of os.uname(), but looking at
/usr/lib/python2.6/site-packages/rpmUtils/arch.py this is not true. It changes it to
ia32e if you have GeniuneIntel in /proc/cpuinfo so the URL is wrong.
$release was undefined and not evaluated.
> Use correct yum variables in repo definition

- src/releasing/quattorpoddoc.py
Before only schema.pan was considered for annotations. This PR adds all pan files for consideration, and skipping those that would provide empty webpages. e.g. mostly:
- config.pan
- config-common.pan
- config-rpm.pan
This brings in about 2000 more lines of documentation that were missed before.
> documentation build: add other pan files

- src/scripts/get-template-library
- Allow to use commits from a PR when building the library (--continuous-integration)
- Used for continous integration of the template library
Not necessarily easy to review (would deserve a full rewrite in a more decent language!) but heavily tested at LAL. Once merged, it should be easy to add PR testing in the template library repositories.
> get-template-library: add support for Travis build environment

- src/releasing/releaser.sh
This gives greater assurance of the integrity of the tags vs. the released packages.
> GPG sign tags during release process

- src/scripts/build_all_repos.sh
The perl version is the concern here and this opens up builds for non-RHEL distributions.
The perl oneliner could be useful for quattor/configuration-modules-core#441
> Check perl version rather than Redhat release number

- src/scripts/build_all_repos.sh
The caller may want to check this and respond to it, so don't obscure it.
> Pass exit codes back when wrapping commands

- src/scripts/build_all_repos.sh
* Use `$*` instead of `$@` when concatenating with a string.
* Declare and export environment variables separately.
* Double quote array expansions, otherwise they're like `$*` and break on spaces.
* Double quote lots of variables to prevent globbing and word splitting.
* Remove unnecessary from `$/${}` arithmetic variables.
* Use globs rather than iterating over `ls` output.
* Quote parameters to `tr` to prevent glob expansion.
* Use `${variable//search/replace}` instead of piping to `sed` where possible.
* Use `$(…)` instead of legacy `` `…` ``.
* Use `[[ ]]` rather than `[ ]` to reduce number of sub-processes.
* Fail script hard if an attempt to change directory fails.
* Remove some stray white-space.
* Ensure that `curl` and `sudo curl`render correctly in wrapped output.
> build_all_repos: Use more bash-isms, address issues flagged by shellcheck

- pom.xml
- quattor-client/pom.xml
- quattor-repo/pom.xml
* Remove reference to decomissioned stratuslab nexus
- Release builder hangs for a long time trying to reach this.
* Bump build tools to latest (1.56) release
- Mostly for consistency
> Clean up and bump build tools to 1.56

- src/scripts/build_all_repos.sh
There shouldn't be any platforms we actually support right now that will build without EPEL being present.
> build-all-repos: Always use EPEL

- src/scripts/plenary_template_library/plenary_template_library.py
* The branch lists haven't been updated in a while and still tried to pull in `emi-2`, so bring these up to date.
* Including hidden files and directories served no purpose, so exclude them from the `rsync`.
> plenary_template_library: Update branch lists and exclude all hidden files

- src/scripts/build_all_repos.sh
* Rejig version checking to allow for more fine-grained dependencies.
* Only sleep if the system actually appears to be a VM.
> Exclude ncm-openstack based on perl version

- src/scripts/plenary_template_library/README.md
- Fix a syntax error (missing `;`)
- Update the template name to `loadpath` to be consistent with the Aquilon [PR](https://github.com/quattor/aquilon/pull/87) in progress
- Slightly different (improved 😄 ) version  of the `loadpath` template
- Order consistent with what was done in SCDB (which seems more sensible in case a template in one template library component is overriden in another template library components).
- Suggestion to move the OS-related loadpath definition to the `config/os/...` expected by Aquilon as it requires the OS version which is normally defined there.
> Plenary templates readme fixes and improvements

- src/scripts/build_all_repos.sh
The previous code assumed the location of the Perl lib directories for each repo, but as POMs represent a hierarchical structure of dependencies this was not always valid, most notably in the case of the configuration-modules-* repos.
This only became an issue when AII became able to use components directly and test cases started making use of this.
The fix also required the special cases for the maven-tools repository to be separated.
Fixes #333.
This has been tested and verified as a fix against the nightly build infrastructure.
> build_all_repos: Find perl targets after compilation

- src/documentation_builder/.coveragerc
- src/documentation_builder/.prospector.yaml
- src/documentation_builder/bin/build-quattor-documentation.sh
- src/documentation_builder/bin/quattor-documentation-builder
- src/documentation_builder/lib/quattordocbuild/builder.py
- src/documentation_builder/lib/quattordocbuild/config.py
- src/documentation_builder/lib/quattordocbuild/jinja/pan.j2
- src/documentation_builder/lib/quattordocbuild/panhandler.py
- src/documentation_builder/lib/quattordocbuild/repo.py
- src/documentation_builder/lib/quattordocbuild/rsthandler.py
- src/documentation_builder/lib/quattordocbuild/sourcehandler.py
- src/documentation_builder/setup.py
- src/documentation_builder/test/builder.py
- src/documentation_builder/test/config.py
- src/documentation_builder/test/panhandler.py
- src/documentation_builder/test/rsthandler.py
- src/documentation_builder/test/sourcehandler.py
- src/documentation_builder/test/testdata/pan_schema_variables.pan
- src/documentation_builder/test/testdata/rst_from_pan.rst
- src/documentation_builder/test/testdata/rst_from_pod.rst
- src/documentation_builder/test/testdata/testconfig.pan
- allows exports of variable annotations
- a lot of the assumptions originally made for configuration-modules-core are taken out and made configurable
> Documentation-builder: rework to be more agnostic

- quattor-repo/src/quattor.repo
This has been the case since 20.12.0.
> quattor-repo: Releases have repositories for major EL versions

- src/rpmlint/config/quattor.toml
e.g. `/usr/share/templates/quattor/metaconfig/cumulus/initialise_sh.tt`
> rpmlint: Allow metaconfig templates to be non-executable scripts

- src/rpmlint/config/quattor.py
- src/rpmlint/config/quattor.toml
- src/scripts/build_all_repos.sh
The last release added a templated script as part of metaconfig, which is non-executable by-design and should not be flagged as an error by `rpmlint` on any platform.
> Add configuration for rpmlint 1.x 

- src/scripts/get-template-library
Would be good to have this fix in 24.10 as the script fails without it (no corresponding tag in this obsolete repo).
> get-template-library: remove obsolete monitoring repository

- src/scripts/get-template-library
Required to debug an issue trying to fix described at https://github.com/quattor/template-library-examples/pull/40#issuecomment-2463021963 (`--continuous-integration` is silently ignored).
> Add debugging information when --continuous integration is present

- src/scripts/get-template-library
Unfortunately tedious to test... I suggest merging if you don't see obvious mistakes and fixing problems if any afterwards. Can be validated by removing TRAVIS variable definitions done as part of https://github.com/quattor/template-library-examples/pull/40.
> get-template-library: add support for GitHub Actions

- src/scripts/get-template-library
Intended to help producing a useful configuration without the need to update the `template-libary-examples` repository at each Quattor version.
No impact on current use in CI tests as what is implemented in this PR was already done when request Quattor version was `HEAD`, like in the CI tests.
> get-template-library: Quattor version update in cluster build properties

- src/scripts/get-template-library
- src/scripts/plenary_template_library/plenary_template_library.py
- `master` is now `main`
- `template-library-grid` and `template-library-os` now have a single `main` branch
Resolves #373.
> Update template library scripts for new repository structure
