quattor/release

.gitignore
src/annotations2html/bin/build-doc.py
src/annotations2html/lib/annotations.css
src/annotations2html/lib/index.html
src/annotations2html/lib/python/panlexer.py
src/annotations2html/lib/python/tpldocutils.py
src/annotations2html/lib/templates/base.html
src/annotations2html/lib/templates/contents.mako
src/annotations2html/lib/templates/nav.mako
src/annotations2html/lib/templates/toplevel.mako
src/annotations2html/lib/templates/unclassified_template.mako
src/annotations2html/lib/transforms/feature.xsl
src/annotations2html/lib/transforms/unclassified.xsl

THE FOLLOWING DISCLAIMER APPLIES TO ALL SOFTWARE CODE
AND OTHER MATERIALS CONTRIBUTED IN CONNECTION WITH THIS
SOFTWARE:
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND
CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE AND ANY WARRANTY OF NON-
INFRINGEMENT, ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR …

Add pan annotation html documentation generator

---

src/releasing/releaser.sh

Tag template-library-openstack during the release

---

src/scripts/build_all_repos.sh
src/scripts/context_init_build_all_repos.sh

Now works flawless on el5 and el6

more bugfixes for el5/el6 build all repos and the contextualisation script

---

quattor-client/pom.xml
quattor-repo/pom.xml

Brings into line with other repos and still builds RPMs.

Switch packaging from rpm to pom

---

src/releasing/quattorpoddoc.py

This allows the code to work as originally intended.

Move email removal block into correct part of the loop

---

src/releasing/quattorpoddoc.py

This should make it much easier to put multiple sets of components in the same set of docs
See http://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation

Build TOC using new syntax

---

src/releasing/releaser.sh

* Try and fix `ulimit -n` automagically.
* Check that dependencies are installed before starting the release.

Deal with release dependencies better

---

src/scripts/build_all_repos.sh

build_all_repos: Test for noreplace bits

---

src/releasing/releaser.sh

This seems to have changed as a result of #101

Correct RPM collection path

---

src/scripts/build_all_repos.sh

Fixes for build_all_repos

---

src/releasing/quattorpoddoc.py

Fixes double parsing of files and subsequently showing up twice.

documentation build: fix duplication bug

---

src/releasing/quattorpoddoc.py

make the descriptions in the schema turn up, and on the correct place.

documentation build bug fixes

---

src/scripts/build_all_repos.sh

build_all_repos: skip whole aii repo on el5, do not try to filter the pom.xml

---

src/scripts/build_last_aq_proto_releases.sh
src/scripts/build_last_aquilon_release.sh

At least one of them should match the aquilon release

Script to build last N aquilon protocol releases and latest aquilon release with RAL customisations

---

src/scripts/build_all_repos.sh

Closes #119, the issue no longer exists with the latest packages.

Remove workaround for broken maven 3.3.3 packages

---

src/scripts/trac2md.py

- Make it Windows-friendly (python path)

trac2md improvements

---

src/scripts/build_all_repos.sh

Vastly improves my ability to trace backwards through the output when something goes wrong.
* Don't use colour if output is not a colour-cabable TTY.
* Identify process output by command name.
* Disambiguate stdout and stderr.

build_all_repos: Wrap and colourise command output when possible

---

src/releasing/releaser.sh

ncm-freeipa and ncm-opennebula can both be used as AII hooks, so their AII
templates need to be included in the AII area of the library.
Function tested standalone in order to produce quattor/template-library-core@96f9ed8d3349f396580a19f6c25f2748932f2b30.

releaser: Copy AII templates for shared core components

---

src/scripts/build_all_repos.sh

Language features such as choice (10.4) and relative prefix statements (10.7) are now commonly used across the codebase.

panc 10.7 is now the minimum supported compiler

---

src/releasing/packager.sh

This is an expanded form of the packaging section of `releaser.sh` which has been used to provide OS specific builds for the last couple of releases.

Add script to build packages from a specific tag

---

src/scripts/get-template-library

More information to help debugging the issue with `--continuous-integration`

Add debugging information when --continuous integration is present
